components:
    schemas:
        TestQueryReq.main:
            properties:
                name:
                    default: test
                    description: name of model validate:required
                    nullable: true
                    type: string
                name1:
                    default: test
                    description: name1 of model validate:required
                    nullable: true
                    type: string
            required:
                - name
                - name1
            type: object
        TestQueryReq1.main:
            properties:
                name:
                    default: test
                    description: name of model validate:required
                    nullable: true
                    type: string
                name1:
                    default: test
                    description: name1 of model validate:required
                    nullable: true
                    type: string
            required:
                - name
                - name1
            type: object
        TestQueryRsp.main:
            properties:
                code:
                    allowEmptyValue: true
                    nullable: true
                    type: integer
                data:
                    additionalProperties: {}
                    allowEmptyValue: true
                    nullable: true
                    type: object
                msg:
                    allowEmptyValue: true
                    nullable: true
                    type: string
            required:
                - code
                - msg
                - data
            type: object
    securitySchemes:
        Basic:
            scheme: basic
            type: http
        Bearer:
            bearerFormat: JWT
            scheme: bearer
            type: http
info:
    contact:
        email: kooksee@163.com
        name: barry
        url: https://github.com/pubgo/opendoc
    description: this is description
    license:
        name: Apache License 2.0
        url: https://github.com/pubgo/opendoc/blob/master/LICENSE
    termsOfService: https://github.com/pubgo
    title: 'this service web title '
    version: 1.0.0
openapi: 3.0.0
paths:
    /api/v1/articles:
        get:
            description: Retrieves a list of articles
            operationId: article_list
            parameters:
                - in: header
                  name: token
                  required: true
                  schema:
                    default: test
                    type: string
                - in: query
                  name: optional
                  required: true
                  schema:
                    type: string
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                properties:
                                    code:
                                        allowEmptyValue: true
                                        nullable: true
                                        type: integer
                                    data:
                                        additionalProperties: {}
                                        allowEmptyValue: true
                                        nullable: true
                                        type: object
                                    msg:
                                        allowEmptyValue: true
                                        nullable: true
                                        type: string
                                required:
                                    - code
                                    - msg
                                    - data
                                type: object
                    description: OK
                default:
                    content:
                        application/json:
                            schema:
                                properties:
                                    code:
                                        allowEmptyValue: true
                                        nullable: true
                                        type: integer
                                    data:
                                        additionalProperties: {}
                                        allowEmptyValue: true
                                        nullable: true
                                        type: object
                                    msg:
                                        allowEmptyValue: true
                                        nullable: true
                                        type: string
                                required:
                                    - code
                                    - msg
                                    - data
                                type: object
                    description: OK
            security:
                - Basic: []
                - Bearer: []
            summary: get article list
            tags:
                - test article service
        post:
            description: Creates a new article with the provided data
            operationId: article_create
            parameters:
                - in: header
                  name: token
                  required: true
                  schema:
                    default: test
                    type: string
                - in: query
                  name: optional
                  required: true
                  schema:
                    type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            properties:
                                name:
                                    default: test
                                    description: name of model validate:required
                                    nullable: true
                                    type: string
                                name1:
                                    default: test
                                    description: name1 of model validate:required
                                    nullable: true
                                    type: string
                            required:
                                - name
                                - name1
                            type: object
                required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                properties:
                                    code:
                                        allowEmptyValue: true
                                        nullable: true
                                        type: integer
                                    data:
                                        additionalProperties: {}
                                        allowEmptyValue: true
                                        nullable: true
                                        type: object
                                    msg:
                                        allowEmptyValue: true
                                        nullable: true
                                        type: string
                                required:
                                    - code
                                    - msg
                                    - data
                                type: object
                    description: OK
                default:
                    content:
                        application/json:
                            schema:
                                properties:
                                    code:
                                        allowEmptyValue: true
                                        nullable: true
                                        type: integer
                                    data:
                                        additionalProperties: {}
                                        allowEmptyValue: true
                                        nullable: true
                                        type: object
                                    msg:
                                        allowEmptyValue: true
                                        nullable: true
                                        type: string
                                required:
                                    - code
                                    - msg
                                    - data
                                type: object
                    description: OK
            security:
                - Basic: []
                - Bearer: []
            summary: create article
            tags:
                - test article service
    /api/v1/articles/{id}:
        delete:
            description: Deletes an article by ID
            operationId: article_delete
            parameters:
                - description: id of model validate:required
                  in: path
                  name: id
                  required: true
                  schema:
                    default: "1"
                    type: integer
                - in: header
                  name: token
                  required: true
                  schema:
                    default: test
                    type: string
                - in: query
                  name: optional
                  required: true
                  schema:
                    type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            properties:
                                name:
                                    default: test
                                    description: name of model validate:required
                                    nullable: true
                                    type: string
                                name1:
                                    default: test
                                    description: name1 of model validate:required
                                    nullable: true
                                    type: string
                            required:
                                - name
                                - name1
                            type: object
                required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                properties:
                                    code:
                                        allowEmptyValue: true
                                        nullable: true
                                        type: integer
                                    data:
                                        additionalProperties: {}
                                        allowEmptyValue: true
                                        nullable: true
                                        type: object
                                    msg:
                                        allowEmptyValue: true
                                        nullable: true
                                        type: string
                                required:
                                    - code
                                    - msg
                                    - data
                                type: object
                    description: OK
                default:
                    content:
                        application/json:
                            schema:
                                properties:
                                    code:
                                        allowEmptyValue: true
                                        nullable: true
                                        type: integer
                                    data:
                                        additionalProperties: {}
                                        allowEmptyValue: true
                                        nullable: true
                                        type: object
                                    msg:
                                        allowEmptyValue: true
                                        nullable: true
                                        type: string
                                required:
                                    - code
                                    - msg
                                    - data
                                type: object
                    description: OK
            security:
                - Basic: []
                - Bearer: []
            summary: delete article
            tags:
                - test article service
        put:
            description: Updates an existing article by ID
            operationId: article_update
            parameters:
                - description: id of model validate:required
                  in: path
                  name: id
                  required: true
                  schema:
                    default: "1"
                    type: integer
                - in: header
                  name: token
                  required: true
                  schema:
                    default: test
                    type: string
                - in: query
                  name: optional
                  required: true
                  schema:
                    type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            properties:
                                name:
                                    default: test
                                    description: name of model validate:required
                                    nullable: true
                                    type: string
                                name1:
                                    default: test
                                    description: name1 of model validate:required
                                    nullable: true
                                    type: string
                            required:
                                - name
                                - name1
                            type: object
                required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                properties:
                                    code:
                                        allowEmptyValue: true
                                        nullable: true
                                        type: integer
                                    data:
                                        additionalProperties: {}
                                        allowEmptyValue: true
                                        nullable: true
                                        type: object
                                    msg:
                                        allowEmptyValue: true
                                        nullable: true
                                        type: string
                                required:
                                    - code
                                    - msg
                                    - data
                                type: object
                    description: OK
                default:
                    content:
                        application/json:
                            schema:
                                properties:
                                    code:
                                        allowEmptyValue: true
                                        nullable: true
                                        type: integer
                                    data:
                                        additionalProperties: {}
                                        allowEmptyValue: true
                                        nullable: true
                                        type: object
                                    msg:
                                        allowEmptyValue: true
                                        nullable: true
                                        type: string
                                required:
                                    - code
                                    - msg
                                    - data
                                type: object
                    description: OK
            security:
                - Basic: []
                - Bearer: []
            summary: update article
            tags:
                - test article service
