components:
    schemas:
        TestFileReq.main:
            type: object
        TestQueryReq.main:
            properties:
                name1:
                    default: test
                    description: name of model validate:required
                    nullable: true
                    type: string
            required:
                - name1
            type: object
        TestQueryReq1.main:
            properties:
                name:
                    default: test
                    description: name of model validate:required
                    nullable: true
                    type: string
                name1:
                    default: test
                    description: name1 of model validate:required
                    nullable: true
                    type: string
                rsp:
                    $ref: '#/components/schemas/TestQueryRsp.main'
            required:
                - name
                - name1
                - rsp
            type: object
        TestQueryReqAAA.main:
            properties:
                name:
                    default: test
                    description: name of model validate:required
                    nullable: true
                    type: string
                name1:
                    default: test
                    description: name1 of model validate:required
                    nullable: true
                    type: string
            required:
                - name
                - name1
            type: object
        TestQueryRsp.main:
            properties:
                name:
                    default: test
                    description: name of model
                    nullable: true
                    type: string
                optional:
                    allowEmptyValue: true
                    nullable: true
                    type: string
                req:
                    $ref: '#/components/schemas/TestQueryReq.main'
                token:
                    default: test
                    nullable: true
                    type: string
                types:
                    description: 类型
                    example:
                        - a
                        - b
                    items:
                        type: string
                    nullable: true
                    readOnly: true
                    type: array
            required:
                - name
                - token
                - optional
                - req
            type: object
    securitySchemes:
        Basic:
            scheme: basic
            type: http
        Bearer:
            bearerFormat: JWT
            scheme: bearer
            type: http
info:
    contact:
        email: kooksee@163.com
        name: barry
        url: https://github.com/pubgo/opendoc
    description: this is description
    license:
        name: Apache License 2.0
        url: https://github.com/pubgo/opendoc/blob/master/LICENSE
    termsOfService: https://github.com/pubgo
    title: 'this service web title '
    version: v0.0.1-dev-99
openapi: 3.0.0
paths:
    /api/v1/articles:
        get:
            operationId: article_list
            parameters:
                - description: name of model validate:required
                  in: query
                  name: name
                  required: true
                  schema:
                    default: test
                    type: string
                - description: required
                  in: header
                  name: token
                  required: true
                  schema:
                    default: test
                    type: string
                - in: query
                  name: optional
                  required: true
                  schema:
                    type: string
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                properties:
                                    name:
                                        default: test
                                        description: name of model
                                        nullable: true
                                        type: string
                                    optional:
                                        allowEmptyValue: true
                                        nullable: true
                                        type: string
                                    req:
                                        $ref: '#/components/schemas/TestQueryReq.main'
                                    token:
                                        default: test
                                        nullable: true
                                        type: string
                                    types:
                                        description: 类型
                                        example:
                                            - a
                                            - b
                                        items:
                                            type: string
                                        nullable: true
                                        readOnly: true
                                        type: array
                                required:
                                    - name
                                    - token
                                    - optional
                                    - req
                                type: object
                    description: OK
                Test:
                    content:
                        application/json:
                            schema:
                                properties:
                                    name:
                                        default: test
                                        description: name of model validate:required
                                        nullable: true
                                        type: string
                                    name1:
                                        default: test
                                        description: name1 of model validate:required
                                        nullable: true
                                        type: string
                                required:
                                    - name
                                    - name1
                                type: object
                    description: Test
                default:
                    content:
                        application/json:
                            schema:
                                properties:
                                    name:
                                        default: test
                                        description: name of model
                                        nullable: true
                                        type: string
                                    optional:
                                        allowEmptyValue: true
                                        nullable: true
                                        type: string
                                    req:
                                        $ref: '#/components/schemas/TestQueryReq.main'
                                    token:
                                        default: test
                                        nullable: true
                                        type: string
                                    types:
                                        description: 类型
                                        example:
                                            - a
                                            - b
                                        items:
                                            type: string
                                        nullable: true
                                        readOnly: true
                                        type: array
                                required:
                                    - name
                                    - token
                                    - optional
                                    - req
                                type: object
                    description: OK
            security:
                - Basic: []
                - Bearer: []
            summary: get article list
            tags:
                - test article service
        post:
            operationId: article_create
            parameters:
                - description: id of model validate:required
                  in: path
                  name: id
                  required: true
                  schema:
                    default: "1"
                    type: integer
                - in: header
                  name: token
                  required: true
                  schema:
                    default: test
                    type: string
                - in: query
                  name: optional
                  required: true
                  schema:
                    type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            properties:
                                name:
                                    default: test
                                    description: name of model validate:required
                                    nullable: true
                                    type: string
                                name1:
                                    default: test
                                    description: name1 of model validate:required
                                    nullable: true
                                    type: string
                                rsp:
                                    $ref: '#/components/schemas/TestQueryRsp.main'
                            required:
                                - name
                                - name1
                                - rsp
                            type: object
                required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                properties:
                                    name:
                                        default: test
                                        description: name of model
                                        nullable: true
                                        type: string
                                    optional:
                                        allowEmptyValue: true
                                        nullable: true
                                        type: string
                                    req:
                                        $ref: '#/components/schemas/TestQueryReq.main'
                                    token:
                                        default: test
                                        nullable: true
                                        type: string
                                    types:
                                        description: 类型
                                        example:
                                            - a
                                            - b
                                        items:
                                            type: string
                                        nullable: true
                                        readOnly: true
                                        type: array
                                required:
                                    - name
                                    - token
                                    - optional
                                    - req
                                type: object
                    description: OK
                default:
                    content:
                        application/json:
                            schema:
                                properties:
                                    name:
                                        default: test
                                        description: name of model
                                        nullable: true
                                        type: string
                                    optional:
                                        allowEmptyValue: true
                                        nullable: true
                                        type: string
                                    req:
                                        $ref: '#/components/schemas/TestQueryReq.main'
                                    token:
                                        default: test
                                        nullable: true
                                        type: string
                                    types:
                                        description: 类型
                                        example:
                                            - a
                                            - b
                                        items:
                                            type: string
                                        nullable: true
                                        readOnly: true
                                        type: array
                                required:
                                    - name
                                    - token
                                    - optional
                                    - req
                                type: object
                    description: OK
            security:
                - Basic: []
                - Bearer: []
            summary: create article
            tags:
                - test article service
    /api/v1/articles/{id}:
        put:
            operationId: article_update
            parameters:
                - description: id of model validate:required
                  in: path
                  name: id
                  required: true
                  schema:
                    default: "1"
                    type: integer
                - in: header
                  name: token
                  required: true
                  schema:
                    default: test
                    type: string
                - in: query
                  name: optional
                  required: true
                  schema:
                    type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            properties:
                                name:
                                    default: test
                                    description: name of model validate:required
                                    nullable: true
                                    type: string
                                name1:
                                    default: test
                                    description: name1 of model validate:required
                                    nullable: true
                                    type: string
                                rsp:
                                    $ref: '#/components/schemas/TestQueryRsp.main'
                            required:
                                - name
                                - name1
                                - rsp
                            type: object
                required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                properties:
                                    name:
                                        default: test
                                        description: name of model
                                        nullable: true
                                        type: string
                                    optional:
                                        allowEmptyValue: true
                                        nullable: true
                                        type: string
                                    req:
                                        $ref: '#/components/schemas/TestQueryReq.main'
                                    token:
                                        default: test
                                        nullable: true
                                        type: string
                                    types:
                                        description: 类型
                                        example:
                                            - a
                                            - b
                                        items:
                                            type: string
                                        nullable: true
                                        readOnly: true
                                        type: array
                                required:
                                    - name
                                    - token
                                    - optional
                                    - req
                                type: object
                    description: OK
                default:
                    content:
                        application/json:
                            schema:
                                properties:
                                    name:
                                        default: test
                                        description: name of model
                                        nullable: true
                                        type: string
                                    optional:
                                        allowEmptyValue: true
                                        nullable: true
                                        type: string
                                    req:
                                        $ref: '#/components/schemas/TestQueryReq.main'
                                    token:
                                        default: test
                                        nullable: true
                                        type: string
                                    types:
                                        description: 类型
                                        example:
                                            - a
                                            - b
                                        items:
                                            type: string
                                        nullable: true
                                        readOnly: true
                                        type: array
                                required:
                                    - name
                                    - token
                                    - optional
                                    - req
                                type: object
                    description: OK
                error:
                    content:
                        application/json:
                            schema:
                                type: object
                    description: error
            security:
                - Basic: []
                - Bearer: []
            summary: update article
            tags:
                - test article service
